### ISSUE TITLE
Headless versie werkt niet bij mij

### ISSUE THREAD

**Issue by murakamifan** [PlaceNL/Bot#14]
Ik probeer de headless versie met behulp van de instructies te installeren maar krijg de volgende error:

` > node bot.js <access-token>`

```
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:724:11)
    at Loader.resolve (internal/modules/esm/loader.js:97:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:50:40)
    at link (internal/modules/esm/module_job.js:49:36) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
```

OS Linux openSUSE Leap 15.3 (maar heb verder weinig verstand van Linux) en browser Firefox.

**Comment by RubenNL** [comment]
Dit lijkt op een versieverschil van Node.js.

Mogelijke oplossing:

```bash
sudo npm install -g n
n lts
```
Sluit je terminal, en open hem opnieuw. Nu zou hij wel moeten werken.

**Comment by murakamifan** [comment]
Bedankt! Helaas heb ik geen admin rechten op deze PC, dus ik zal toch maar de 'gewone' versie gebruiken.
